### ISSUE TITLE
error when sbt start

### ISSUE THREAD

**Issue by shellyan** [fxthomas/android-scratch#1]
[error] Android NDK not found.  You might need to set ANDROID_NDK_HOME or ANDROID_NDK_ROOT

I dont why what the heck it requires NDK? not SDK, is this a typo?

I followed the post  `First snapshot for SBT-Android 0.7` and sbt-publish-local.

**Comment by fxthomas** [comment]
That's a bug, good thing you stumbled upon it ;)

I just pushed a fix to my branch, can you pull and try again?

**Comment by shellyan** [comment]
thank you 
you can close it now
